DROP TABLE IF EXISTS Tilaus CASCADE;
DROP TABLE IF EXISTS Tila CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Rooli CASCADE;
DROP TABLE IF EXISTS Tuote CASCADE;
DROP TABLE IF EXISTS Kategoria CASCADE;
DROP TABLE IF EXISTS KayttajaRooli CASCADE;
DROP TABLE IF EXISTS Tuoteilmentyma CASCADE;
