DROP TABLE IF EXISTS Order1 CASCADE;
DROP TABLE IF EXISTS Status CASCADE;
DROP TABLE IF EXISTS User1 CASCADE;
DROP TABLE IF EXISTS Role CASCADE;
DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS UserRole CASCADE;
DROP TABLE IF EXISTS ProductInstance CASCADE;
